Repository hpi-swt2/lecture-portal, pull requests merged in 2019-12, with the labels that each got.

#64 Feature/#48 current lecture view
  app/controllers/lectures_controller.rb
  app/models/lecture.rb
  app/views/lectures/current.html.erb
  config/routes.rb
  db/schema.rb
  spec/features/lectures/current_lecture_spec.rb
  spec/views/lectures/current.html.erb_spec.rb
Labels: Team RESTless

#75 A lecturer can start a poll
  app/controllers/polls_controller.rb
  app/javascript/components/PollOption.tsx
  app/models/lecture.rb
  app/models/poll.rb
  app/models/poll_option.rb
  app/views/lectures/show.html.erb
  app/views/polls/_form.html.erb
  app/views/polls/edit.html.erb
  app/views/polls/index.html.erb
  app/views/polls/new.html.erb
  app/views/polls/show.html.erb
  config/routes.rb
  db/migrate/20191122143224_add_polls_to_lecture.rb
  db/migrate/20191122145046_change_poll_lecture_relation.rb
  db/migrate/20191204101435_add_is_active_to_poll.rb
  db/schema.rb
  package.json
  spec/controllers/polls_controller_spec.rb
  spec/factories/polls.rb
  spec/models/poll_option_spec.rb
  spec/requests/polls_spec.rb
  spec/routing/polls_routing_spec.rb
  spec/views/polls/edit.html.erb_spec.rb
  spec/views/polls/index.html.erb_spec.rb
  spec/views/polls/new.html.erb_spec.rb
  spec/views/polls/show.html.erb_spec.rb
  yarn.lock
Labels: Team S⊙w⊙T

#81 feature/Questions
  Gemfile
  Gemfile.lock
  app/assets/javascripts/cable.js
  app/assets/javascripts/channels/.keep
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/questions.scss
  app/channels/application_cable/connection.rb
  app/channels/questions_channel.rb
  app/controllers/api/questions_controller.rb
  app/controllers/questions_controller.rb
  app/helpers/questions_helper.rb
  app/javascript/components/.keep
  app/javascript/components/Questions.tsx
  app/javascript/components/QuestionsForm.tsx
  app/javascript/components/QuestionsList.tsx
  app/javascript/components/constants.ts
  app/javascript/packs/hello_react.jsx
  app/javascript/packs/hello_typescript.ts
  app/models/question.rb
  app/models/user.rb
  app/serializers/question_serializer.rb
  app/views/questions/index.html.erb
  config/cable.yml
  config/routes.rb
  db/migrate/20191129170411_create_questions.rb
  db/schema.rb
  package.json
  spec/controllers/api/questions_controller_spec.rb
  spec/controllers/questions_controller_spec.rb
  spec/factories/questions.rb
  spec/models/question_spec.rb
  spec/routing/api/questions_routing_spec.rb
  spec/routing/questions_routing_spec.rb
  tsconfig.json
  yarn.lock
Labels: Team PB

#65 feature/#22 lecturer create new lecture
  .travis.yml
  README.md
  app/controllers/lectures_controller.rb
  app/models/lecture.rb
  app/models/user.rb
  app/views/lectures/_form.html.erb
  app/views/lectures/edit.html.erb
  app/views/lectures/index.html.erb
  app/views/lectures/new.html.erb
  app/views/lectures/show.html.erb
  app/views/polls/show.html.erb
  db/migrate/20191115134255_create_lectures.rb
  db/migrate/20191122100734_create_polls.rb
  db/migrate/20191128093012_add_defaults_to_lecture.rb
  db/migrate/20191129161543_add_lecturer_ref_to_lecture.rb
  db/migrate/20191130141928_create_join_table_student_lecture.rb
  db/schema.rb
  db/seeds.rb
  spec/controllers/lectures_controller_spec.rb
  spec/factories/lectures.rb
  spec/features/lectures/current_lecture_spec.rb
  spec/models/lecture_spec.rb
  spec/models/user_spec.rb
  spec/requests/lectures_spec.rb
  spec/views/lectures/current.html.erb_spec.rb
  spec/views/lectures/edit.html.erb_spec.rb
  spec/views/lectures/index.html.erb_spec.rb
  spec/views/lectures/new.html.erb_spec.rb
  spec/views/lectures/show.html.erb_spec.rb
Labels: Team RESTless

#85 Bugfix/handle non existent current user
  app/controllers/lectures_controller.rb
  app/controllers/polls_controller.rb
  spec/controllers/lectures_controller_spec.rb
  spec/controllers/polls_controller_spec.rb
  spec/requests/polls_spec.rb
  spec/views/polls/edit.html.erb_spec.rb
  spec/views/polls/index.html.erb_spec.rb
Labels: Team S⊙w⊙T, bug, testing

#70 Feature/#40 starting lectures
  app/controllers/lectures_controller.rb
  app/models/lecture.rb
  app/views/lectures/current.html.erb
  app/views/lectures/index.html.erb
  app/views/lectures/show.html.erb
  config/routes.rb
  spec/controllers/lectures_controller_spec.rb
  spec/factories/lectures.rb
  spec/factories/users.rb
  spec/features/lectures/all_lectures_spec.rb
  spec/features/lectures/show_lecture_spec.rb
Labels: Team RESTless

#63 Feature/#31 student feedback
  .rubocop_todo.yml
  app/assets/javascripts/application.js
  app/assets/javascripts/feedbacks.js
  app/assets/stylesheets/feedbacks.scss
  app/controllers/feedbacks_controller.rb
  app/controllers/lectures_controller.rb
  app/helpers/feedbacks_helper.rb
  app/models/feedback.rb
  app/models/lecture.rb
  app/views/lectures/show.html.erb
  config/routes.rb
  db/migrate/20191128173809_create_feedbacks.rb
  db/schema.rb
  spec/controllers/feedbacks_controller_spec.rb
  spec/factories/feedbacks.rb
  spec/helpers/feedbacks_helper_spec.rb
  spec/models/feedback_spec.rb
  spec/views/lectures/show.html.erb_spec.rb
Labels: Team Überlapsch

#60 Feature/#35 Add tab view
  spec/views/lectures/show.html.erb_spec.rb
Labels: WIP

#99 Add votes attribut to poll options db schema
  app/models/poll_option.rb
  db/migrate/20191206144904_add_votes_to_poll_option.rb
  db/schema.rb
Labels: Team S⊙w⊙T

#102 Fixed continuous deployment.
  Dockerfile
  db/migrate/20191115134255_create_lectures.rb
  db/migrate/20191128093013_add_questions_enabled_to_lectures.rb
  db/migrate/20191128093014_add_defaults_to_lecture.rb
  deployment.sh
Labels: Team RESTless

#105 Feature/#15 questions resolving
  app/assets/stylesheets/questions.scss
  app/channels/question_resolving_channel.rb
  app/controllers/api/questions_controller.rb
  app/javascript/components/Question.tsx
  app/javascript/components/Questions.tsx
  app/javascript/components/QuestionsApp.tsx
  app/javascript/components/QuestionsForm.tsx
  app/javascript/components/QuestionsList.tsx
  app/javascript/hooks/useInject.ts
  app/javascript/stores/CurrentQuestion.ts
  app/javascript/stores/Question.ts
  app/javascript/stores/QuestionsList.ts
  app/javascript/stores/QuestionsRootStore.ts
  app/javascript/stores/createStore.ts
  app/javascript/utils/QuestionsUtils.ts
  app/javascript/utils/constants.ts
  app/views/questions/index.html.erb
  config/routes.rb
  db/migrate/20191205104744_add_resolved_to_question.rb
  db/schema.rb
  package.json
  spec/controllers/api/questions_controller_spec.rb
  yarn.lock
Labels: Team PB

#108 feature/#47 student leave lecture
  app/controllers/lectures_controller.rb
  app/models/lecture.rb
  app/views/lectures/show.html.erb
  config/routes.rb
  spec/controllers/lectures_controller_spec.rb
  spec/features/lectures/show_lecture_spec.rb
  spec/models/lecture_spec.rb
  spec/views/lectures/show.html.erb_spec.rb
Labels: Team RESTless

#106 Feature/#71 question upvotes
  app/assets/stylesheets/questions.scss
  app/channels/question_upvoting_channel.rb
  app/controllers/api/questions_controller.rb
  app/javascript/components/Question.tsx
  app/javascript/components/QuestionsList.tsx
  app/javascript/stores/Question.ts
  app/javascript/stores/QuestionsList.ts
  app/javascript/utils/QuestionsUtils.ts
  app/models/question.rb
  app/models/user.rb
  app/serializers/question_serializer.rb
  config/routes.rb
  db/migrate/20191206134114_create_join_table_upvoting.rb
  db/schema.rb
  spec/controllers/api/questions_controller_spec.rb
  spec/models/question_spec.rb
  spec/models/user_spec.rb
Labels: Team PB

#112 Feature/#38 ended lectures
  app/controllers/lectures_controller.rb
  app/views/lectures/index.html.erb
  spec/controllers/lectures_controller_spec.rb
  spec/views/lectures/index.html.erb_spec.rb
Labels: Team RESTless

#111 add Review Button
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/lectures.scss
  app/views/lectures/index.html.erb
  spec/views/lectures/index.html.erb_spec.rb
Labels: Team RESTless

#114 Fix bug and integrate regession test
  app/controllers/lectures_controller.rb
  db/schema.rb
  spec/controllers/lectures_controller_spec.rb
  spec/factories/lectures.rb
Labels: Team RESTless

#115 Feature/#72 question upvote sorting
  app/assets/stylesheets/questions.scss
  app/controllers/api/questions_controller.rb
  app/javascript/components/Question.tsx
  app/javascript/components/QuestionsApp.tsx
  app/javascript/components/QuestionsList.tsx
  app/javascript/stores/Question.ts
  app/javascript/stores/QuestionsList.ts
  app/javascript/stores/QuestionsRootStore.ts
  app/javascript/utils/QuestionsUtils.ts
  app/serializers/question_serializer.rb
  spec/controllers/api/questions_controller_spec.rb
Labels: Team PB

#116 Feature/#83 Implement and test file upload.
  .travis.yml
  Gemfile
  Gemfile.lock
  app/assets/javascripts/uploaded_files.js
  app/assets/stylesheets/uploaded_files.scss
  app/controllers/uploaded_files_controller.rb
  app/helpers/uploaded_files_helper.rb
  app/models/lecture.rb
  app/models/uploaded_file.rb
  app/serializers/uploaded_file_serializer.rb
  app/views/files/new.html.erb
  app/views/lectures/_table.html.erb
  app/views/uploaded_files/_form.html.erb
  app/views/uploaded_files/index.html.erb
  app/views/uploaded_files/new.html.erb
  config/routes.rb
  db/migrate/20191219102226_add_files_schema.rb
  db/schema.rb
  spec/controllers/polls_controller_spec.rb
  spec/controllers/uploaded_files_controller_spec.rb
  spec/factories/uploaded_files.rb
  spec/features/all_uploaded_files_spec.rb
  spec/fixtures/files/LICENSE
  spec/helpers/uploaded_files_helper_spec.rb
  spec/models/uploaded_file_spec.rb
  spec/routing/uploaded_files_routing_spec.rb
Labels: Team RESTless

#110 Feature/#45 edit lectures
  app/controllers/lectures_controller.rb
  app/views/lectures/_form.html.erb
  app/views/lectures/_table.html.erb
  app/views/lectures/edit.html.erb
  app/views/lectures/new.html.erb
  app/views/lectures/show.html.erb
  spec/controllers/lectures_controller_spec.rb
  spec/features/lectures/all_lectures_spec.rb
  spec/views/lectures/show.html.erb_spec.rb
Labels: Team RESTless

#136 Feature/#122 file download
  app/controllers/uploaded_files_controller.rb
  app/views/uploaded_files/index.html.erb
  config/routes.rb
  spec/features/all_uploaded_files_spec.rb
Labels: Team RESTless

#139 Feature/#74 assign questions to lecture
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/lecture_updates.scss
  app/assets/stylesheets/lectures.scss
  app/assets/stylesheets/questions.scss
  app/channels/question_resolving_channel.rb
  app/channels/question_upvoting_channel.rb
  app/channels/questions_channel.rb
  app/controllers/api/questions_controller.rb
  app/controllers/questions_controller.rb
  app/javascript/components/Question.tsx
  app/javascript/components/QuestionsApp.tsx
  app/javascript/components/QuestionsForm.tsx
  app/javascript/components/QuestionsList.tsx
  app/javascript/components/Update.tsx
  app/javascript/components/UpdatesApp.tsx
  app/javascript/components/UpdatesList.tsx
  app/javascript/hooks/useInject.ts
  app/javascript/packs/application.js
  app/javascript/stores/CurrentQuestion.ts
  app/javascript/stores/Question.ts
  app/javascript/stores/QuestionsList.ts
  app/javascript/stores/QuestionsRootStore.ts
  app/javascript/stores/UpdateItem.ts
  app/javascript/stores/UpdatesList.ts
  app/javascript/stores/UpdatesRootStore.ts
  app/javascript/stores/createQuestionsStore.ts
  app/javascript/stores/createUpdatesStore.ts
  app/javascript/utils/QuestionsActionCable.ts
  app/javascript/utils/QuestionsUtils.ts
  app/javascript/utils/UpdatesUtils.ts
  app/models/question.rb
  app/views/lectures/show.html.erb
  config/cable.yml
  config/routes.rb
  db/migrate/20191219093245_add_lecture_to_question.rb
  db/schema.rb
  spec/controllers/api/questions_controller_spec.rb
  spec/controllers/questions_controller_spec.rb
  spec/factories/questions.rb
  spec/models/question_spec.rb
  spec/routing/api/questions_routing_spec.rb
  spec/routing/questions_routing_spec.rb
Labels: Team PB

#118 Feature/#21 show poll results
  app/controllers/polls_controller.rb
  app/javascript/components/AnswerOption.tsx
  app/javascript/components/PollOption.tsx
  app/models/answer.rb
  app/models/poll.rb
  app/views/polls/_answer_form.html.erb
  app/views/polls/answer.html.erb
  app/views/polls/edit.html.erb
  app/views/polls/show.html.erb
  config/routes.rb
  db/migrate/20191206130656_create_answer.rb
  db/migrate/20191206131227_add_refs_to_answers.rb
  db/schema.rb
  spec/controllers/polls_controller_spec.rb
  spec/factories/answers.rb
  spec/views/polls/show.html.erb_spec.rb
Labels: Story, Team S⊙w⊙T
