Repository hpi-swt2/lecture-portal, pull requests merged in 2019-11, with the labels that each got.

#29 Create pull_request_template.md
  .github/pull_request_template.md
Labels: tech leads

#28 Feature/#8 lecture model
  Gemfile
  app/assets/javascripts/lectures.js
  app/assets/stylesheets/lectures.scss
  app/assets/stylesheets/scaffolds.scss
  app/controllers/lectures_controller.rb
  app/helpers/lectures_helper.rb
  app/models/lecture.rb
  app/views/lectures/_form.html.erb
  app/views/lectures/edit.html.erb
  app/views/lectures/index.html.erb
  app/views/lectures/new.html.erb
  app/views/lectures/show.html.erb
  config/routes.rb
  db/migrate/20191115134255_create_lectures.rb
  db/schema.rb
  spec/controllers/lectures_controller_spec.rb
  spec/factories/lectures.rb
  spec/models/lecture_spec.rb
  spec/requests/lectures_spec.rb
  spec/routing/lectures_routing_spec.rb
  spec/views/lectures/edit.html.erb_spec.rb
  spec/views/lectures/index.html.erb_spec.rb
  spec/views/lectures/new.html.erb_spec.rb
  spec/views/lectures/show.html.erb_spec.rb
Labels: Team S⊙w⊙T

#50 Feature/#10 poll model
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  app/assets/javascripts/polls.js
  app/assets/stylesheets/polls.scss
  app/controllers/polls_controller.rb
  app/helpers/polls_helper.rb
  app/models/poll.rb
  app/models/poll_option.rb
  app/views/polls/_form.html.erb
  app/views/polls/edit.html.erb
  app/views/polls/index.html.erb
  app/views/polls/new.html.erb
  app/views/polls/show.html.erb
  config/routes.rb
  db/migrate/20191122100734_create_polls.rb
  db/migrate/20191122102114_create_poll_options.rb
  db/schema.rb
  spec/controllers/polls_controller_spec.rb
  spec/factories/poll_options.rb
  spec/factories/polls.rb
  spec/helpers/polls_helper_spec.rb
  spec/models/poll_option_spec.rb
  spec/models/poll_spec.rb
  spec/requests/polls_spec.rb
  spec/routing/polls_routing_spec.rb
  spec/views/polls/edit.html.erb_spec.rb
  spec/views/polls/index.html.erb_spec.rb
  spec/views/polls/new.html.erb_spec.rb
  spec/views/polls/show.html.erb_spec.rb
Labels: Team RESTless

#43 Add pullapprove
  .pullapprove.yml
Labels: Team S⊙w⊙T

#59 Added continuous deployment to heroku.
  .browserslistrc
  .dockerignore
  .gitignore
  .travis.yml
  Dockerfile
  Gemfile
  Gemfile.lock
  README.md
  app/javascript/components/.keep
  app/javascript/packs/application.js
  app/javascript/packs/hello_react.jsx
  app/javascript/packs/hello_typescript.ts
  app/javascript/packs/server_rendering.js
  app/views/layouts/application.html.erb
  babel.config.js
  bin/webpack
  bin/webpack-dev-server
  build.sh
  cmd.sh
  config/database.yml
  config/webpack/development.js
  config/webpack/environment.js
  config/webpack/loaders/typescript.js
  config/webpack/production.js
  config/webpack/test.js
  config/webpacker.yml
  db/schema.rb
  deployment.sh
  docker-compose.yml
  package.json
  postcss.config.js
  tsconfig.json
  yarn.lock
Labels: Team RESTless

#66 update pullapprove for team RESTless
  .pullapprove.yml
Labels: Team RESTless
