Repository hpi-swt2/lecture-portal, pull requests merged in 2020-01, with the labels that each got.

#120 Feature/#20 poll can be closed
  .gitignore
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/lectures.scss
  app/assets/stylesheets/polls.scss
  app/controllers/lectures_controller.rb
  app/controllers/polls_controller.rb
  app/javascript/components/AnswerOption.tsx
  app/models/poll.rb
  app/views/lectures/index.html.erb
  app/views/lectures/show.html.erb
  app/views/polls/_answer_form.html.erb
  app/views/polls/_form.html.erb
  app/views/polls/index.html.erb
  app/views/polls/index_students.html.erb
  app/views/polls/show.html.erb
  config/routes.rb
  db/migrate/20191129151616_add_is_active_to_poll.rb
  db/schema.rb
  package.json
  spec/controllers/polls_controller_spec.rb
  spec/factories/polls.rb
  spec/models/poll_spec.rb
  spec/views/polls/index.html.erb_spec.rb
  spec/views/polls/show.html.erb_spec.rb
  yarn.lock
Labels: WIP

#140 Fix startup crashes on heroku
  Dockerfile
Labels: Team RESTless, bug

#144 Fix is_active migration
  db/migrate/20191204101435_add_is_active_to_poll.rb
  db/migrate/20191204101436_change_is_active_default.rb
  deployment.sh
Labels: Team RESTless, bug

#177 Feature/#83 associate file with course
  app/models/course.rb
  app/models/lecture.rb
  spec/features/uploadedFiles/all_uploaded_files_spec.rb
  spec/features/uploadedFiles/uploaded_file_association_spec.rb
Labels: Team RESTless

#179 Feature/#83 files have authorship timestamps
  app/controllers/uploaded_files_controller.rb
  app/models/uploaded_file.rb
  app/models/user.rb
  db/migrate/20200110150053_add_user_to_uploaded_files.rb
  db/schema.rb
  spec/features/uploadedFiles/all_uploaded_files_spec.rb
  spec/features/uploadedFiles/uploaded_file_association_spec.rb
Labels: Team RESTless, ready to merge

#128 Move leave/end lecture button into tabbar
  app/models/lecture.rb
  app/views/lectures/_form.html.erb
  app/views/lectures/_tabbar.html.erb
  app/views/lectures/show.html.erb
  spec/controllers/lectures_controller_spec.rb
  spec/features/lectures/show_lecture_spec.rb
  spec/models/lecture_spec.rb
  spec/views/lectures/edit.html.erb_spec.rb
  spec/views/lectures/show.html.erb_spec.rb
Labels: Team RESTless, ready to merge

#186 refactor course lectures overview to use table
  app/views/courses/_table.html.erb
  app/views/courses/show.html.erb
  app/views/lectures/_table.html.erb
  spec/features/courses/show_course_spec.rb
Labels: Team RESTless, design leads, ready to merge

#168 Feature/#62 archive ended lectures
  app/models/lecture.rb
  spec/models/lecture_spec.rb
Labels: Team RESTless

#182 Improvement/#146 integrate poll interaction into tabview without react
  app/assets/stylesheets/polls.scss
  app/controllers/polls_controller.rb
  app/views/layouts/application.html.erb
  app/views/lectures/show.html.erb
  app/views/polls/_lecturer_table.html.erb
  app/views/polls/_student_table.html.erb
  app/views/polls/index.html.erb
  app/views/polls/index_students.html.erb
  app/views/polls/show.html.erb
  config/routes.rb
  spec/controllers/polls_controller_spec.rb
  spec/views/polls/show.html.erb_spec.rb
Labels: Team S⊙w⊙T

#190 fix path
  app/views/lectures/show.html.erb
Labels: bug

#121 Feature/#107 design of lecture create page
  app/views/lectures/_form.html.erb
  app/views/lectures/edit.html.erb
  app/views/lectures/new.html.erb
  spec/views/lectures/edit.html.erb_spec.rb
  spec/views/lectures/new.html.erb_spec.rb
  spec/views/lectures/show.html.erb_spec.rb
Labels: Team RESTless

#189 Feature/#155 course file view
  app/assets/stylesheets/courses.scss
  app/controllers/courses_controller.rb
  app/models/uploaded_file.rb
  app/views/courses/_filelist.html.erb
  app/views/courses/show.html.erb
  spec/features/courses/show_course_spec.rb
  spec/views/courses/show.html.erb_spec.rb
Labels: ready to merge

#187 Install Mergify Tool
  .mergify.yml
  README.md
Labels: Scrum Master, WIP, question

#129 add some seed users & lectures
  db/seeds.rb
Labels: Scrum Master

#191 Feature/#160 remove files course overview
  app/controllers/uploaded_files_controller.rb
  app/views/courses/_filelist.html.erb
  config/routes.rb
  spec/controllers/uploaded_files_controller_spec.rb
  spec/features/courses/show_course_spec.rb
Labels: Team RESTless, ready to merge

#198 Feature/#167 rejoin entered lecture
  app/controllers/lectures_controller.rb
  spec/controllers/lectures_controller_spec.rb
  spec/factories/lectures.rb
Labels: Team S⊙w⊙T

#206 Feature/#165 need key to join lecture
  app/controllers/lectures_controller.rb
  app/views/courses/_table_only_running.erb
  app/views/home/index.html.erb
  spec/controllers/lectures_controller_spec.rb
  spec/features/lectures/current_lecture_spec.rb
  spec/views/courses/show.html.erb_spec.rb
  spec/views/home/index.html.erb_spec.rb
Labels: Team S⊙w⊙T, ready to merge

#193 Improvement/#146 make poll views better
  app/assets/stylesheets/polls.scss
  app/javascript/components/PollOption.tsx
  app/views/polls/answer.html.erb
  app/views/polls/edit.html.erb
  app/views/polls/index.html.erb
  app/views/polls/index_students.html.erb
  spec/views/polls/edit.html.erb_spec.rb
Labels: Team S⊙w⊙T

#188 #166 add enrollment key tab for lecturer
  app/assets/stylesheets/lectures.scss
  app/views/lectures/_form.html.erb
  app/views/lectures/_tabbar.html.erb
  app/views/lectures/show.html.erb
  spec/views/lectures/show.html.erb_spec.rb
Labels: Team S⊙w⊙T

#209 add notice pages when polls or questions are disabled
  app/views/lectures/show.html.erb
  spec/views/lectures/show.html.erb_spec.rb
Labels: Team S⊙w⊙T

#178 Feature/#125 upload links
  app/controllers/lectures_controller.rb
  app/controllers/uploaded_files_controller.rb
  app/models/uploaded_file.rb
  app/views/components/_show_uploaded_files_or_links.erb
  app/views/courses/_filelist.html.erb
  app/views/courses/_table_not_running.html.erb
  app/views/courses/_table_only_running.erb
  app/views/courses/show.html.erb
  app/views/home/index.html.erb
  app/views/lectures/show.html.erb
  app/views/uploaded_files/_form.html.erb
  app/views/uploaded_files/index.html.erb
  db/migrate/20200110152851_add_is_link_to_uploaded_files.rb
  db/migrate/20200110154810_change_is_link_default.rb
  db/schema.rb
  spec/controllers/uploaded_files_controller_spec.rb
  spec/features/courses/show_course_spec.rb
  spec/features/uploadedFiles/all_uploaded_files_spec.rb
  spec/features/uploadedFiles/uploaded_files_View_in_dashboard_spec.rb
  spec/features/uploadedFiles/uploaded_links_spec.rb
  spec/features/uploadedFiles/uplod_new_file_spec.rb
  spec/fixtures/files/FileWithUmlautsÜÖÄüöä
  spec/spec_helper.rb
Labels: Team RESTless, ready to merge

#205 Add question filtering depending on resolve status
  app/assets/stylesheets/courses.scss
  app/assets/stylesheets/questions.scss
  app/controllers/questions_controller.rb
  app/javascript/components/Question.tsx
  app/javascript/components/QuestionsList.tsx
  app/javascript/components/UpdatesList.tsx
  app/javascript/stores/Question.ts
  app/javascript/stores/QuestionsList.ts
  app/javascript/stores/UpdateItem.ts
  app/serializers/question_serializer.rb
  spec/controllers/questions_controller_spec.rb
Labels: Team PB

#207 Feature/#73 disallow question interaction in archived lecture
  app/assets/stylesheets/lecture_updates.scss
  app/assets/stylesheets/questions.scss
  app/controllers/questions_controller.rb
  app/javascript/components/QuestionsApp.tsx
  app/javascript/components/QuestionsForm.tsx
  app/javascript/components/QuestionsList.tsx
  app/javascript/components/Update.tsx
  app/javascript/components/UpdatesApp.tsx
  app/javascript/stores/Question.ts
  app/javascript/stores/QuestionsRootStore.ts
  app/javascript/stores/UpdatesRootStore.ts
  app/models/lecture.rb
  app/views/lectures/show.html.erb
Labels: Team PB

#204 Feature/#147 add comprehension to lecture
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/lecture_comprehension.scss
  app/assets/stylesheets/lecture_dashboard.scss
  app/assets/stylesheets/lecture_updates.scss
  app/assets/stylesheets/lectures.scss
  app/channels/comprehension_stamp_channel.rb
  app/controllers/lectures_controller.rb
  app/controllers/questions_controller.rb
  app/javascript/components/ComprehensionApp.tsx
  app/javascript/components/ComprehensionLecturer.tsx
  app/javascript/components/ComprehensionStudent.tsx
  app/javascript/components/QuestionsApp.tsx
  app/javascript/components/UpdatesApp.tsx
  app/javascript/hooks/useInject.ts
  app/javascript/stores/ComprehensionRootStore.ts
  app/javascript/stores/CurrentQuestion.ts
  app/javascript/stores/Question.ts
  app/javascript/stores/createComprehensionStore.ts
  app/javascript/utils/ComprehensionActionCable.ts
  app/javascript/utils/ComprehensionUtils.ts
  app/javascript/utils/QuestionsUtils.ts
  app/javascript/utils/UpdatesUtils.ts
  app/javascript/utils/constants.ts
  app/models/lecture.rb
  app/models/lecture_comprehension_stamp.rb
  app/views/lectures/show.html.erb
  config/application.rb
  config/routes.rb
  db/migrate/20200109103908_create_comprehension_stamps.rb
  db/schema.rb
  spec/controllers/lectures_controller_spec.rb
  spec/factories/lecturecomprehensionstamp.rb
  spec/models/lecture_comprehension_stamp_spec.rb
Labels: Team PB

#216 Disable upvoting and resolving for resolved questions
  app/assets/stylesheets/questions.scss
  app/controllers/questions_controller.rb
Labels: Team PB

#213 Feature/#192 list of participating students
  app/views/lectures/show.html.erb
  spec/views/lectures/show.html.erb_spec.rb
Labels: Team S⊙w⊙T

#208 Add button to delete a course in the course settings
  app/controllers/courses_controller.rb
  app/controllers/feedbacks_controller.rb
  app/controllers/lectures_controller.rb
  app/controllers/polls_controller.rb
  app/controllers/questions_controller.rb
  app/views/courses/_form.html.erb
  app/views/courses/edit.html.erb
  app/views/courses/index.html.erb
  app/views/lectures/_form.html.erb
  spec/controllers/courses_controller_spec.rb
  spec/controllers/feedbacks_controller_spec.rb
  spec/controllers/lectures_controller_spec.rb
  spec/controllers/polls_controller_spec.rb
  spec/controllers/questions_controller_spec.rb
  spec/views/courses/edit.html.erb_spec.rb
Labels: Team S⊙w⊙T

#223 Feature/#220 filter ui
  app/javascript/components/QuestionsList.tsx
  app/javascript/stores/QuestionsList.ts
Labels: Team PB

#212 Feature/#158 upload files to lectures
  app/assets/stylesheets/courses.scss
  app/controllers/uploaded_files_controller.rb
  app/views/components/_show_uploaded_files_or_links.erb
  app/views/courses/_table.html.erb
  app/views/courses/_table_not_running.html.erb
  app/views/courses/_table_only_running.erb
  app/views/courses/show.html.erb
  app/views/lectures/_form.html.erb
  app/views/lectures/_tabbar.html.erb
  app/views/lectures/show.html.erb
  app/views/uploaded_files/_form.html.erb
  app/views/uploaded_files/index.html.erb
  app/views/uploaded_files/new.html.erb
  config/routes.rb
  spec/controllers/uploaded_files_controller_spec.rb
  spec/features/courses/show_course_spec.rb
  spec/features/lectures/show_lecture_spec.rb
  spec/features/lectures/upload_files_to_lectures_spec.rb
  spec/features/uploadedFiles/all_uploaded_files_spec.rb
  spec/features/uploadedFiles/uploaded_links_spec.rb
  spec/features/uploadedFiles/uplod_new_file_spec.rb
  spec/routing/uploaded_files_routing_spec.rb
  spec/views/lectures/show.html.erb_spec.rb
Labels: Team RESTless

#224 Disable comprehension voting after the lecture has ended
  app/assets/stylesheets/lecture_comprehension.scss
  app/javascript/components/ComprehensionApp.tsx
  app/javascript/components/ComprehensionStudent.tsx
  app/javascript/stores/ComprehensionRootStore.ts
  app/views/lectures/show.html.erb
Labels: Team PB

#228 Feature/#222 lecturer dashboard statistics
  app/assets/stylesheets/lecture_dashboard.scss
  app/assets/stylesheets/lecture_statistics.scss
  app/assets/stylesheets/lectures.scss
  app/channels/students_statistics_channel.rb
  app/controllers/lectures_controller.rb
  app/javascript/components/ComprehensionApp.tsx
  app/javascript/components/StatisticsApp.tsx
  app/javascript/components/StatisticsView.tsx
  app/javascript/hooks/useInject.ts
  app/javascript/stores/StatisticsRootStore.ts
  app/javascript/stores/createStatisticsStore.ts
  app/javascript/utils/QuestionsActionCable.ts
  app/javascript/utils/StatisticsUtils.ts
  app/javascript/utils/StudentsActionCable.ts
  app/views/lectures/show.html.erb
  spec/controllers/lectures_controller_spec.rb
Labels: Team PB

#231 Improve React apps data loading
  app/controllers/lectures_controller.rb
  app/controllers/questions_controller.rb
  app/javascript/components/ComprehensionApp.tsx
  app/javascript/components/QuestionsApp.tsx
  app/javascript/components/UpdatesApp.tsx
  app/javascript/utils/ComprehensionUtils.ts
  app/javascript/utils/QuestionsUtils.ts
  app/javascript/utils/UpdatesUtils.ts
  app/models/lecture.rb
  app/models/question.rb
  app/views/lectures/show.html.erb
  spec/controllers/lectures_controller_spec.rb
  spec/controllers/questions_controller_spec.rb
  spec/models/lecture_spec.rb
  spec/models/question_spec.rb
Labels: Team PB

#232 Change comprehension colors
  app/assets/stylesheets/lecture_comprehension.scss
  app/javascript/utils/constants.ts
Labels: Team PB

#217 Feature/#169 feedback submit visualized
  app/controllers/feedbacks_controller.rb
  app/models/feedback.rb
  app/models/user.rb
  app/views/lectures/show.html.erb
  app/views/polls/_form.html.erb
  db/migrate/20200112153429_add_user_to_feedback.rb
  db/migrate/20200112153848_add_feedback_to_user.rb
  db/schema.rb
  spec/factories/feedbacks.rb
  spec/views/home/index.html.erb_spec.rb
Labels: Team Überlapsch

#233 Improve comprehension items alignment
  app/assets/stylesheets/lecture_comprehension.scss
Labels: Team PB

#251 Fix comprehension disabled after lecture ended
  app/views/lectures/show.html.erb
Labels: Team PB

#250 Fix issue #246
  app/views/layouts/application.html.erb
Labels: Team S⊙w⊙T

#211 Improvement/#210 unify behaviour when kicked from lecture
  app/controllers/feedbacks_controller.rb
  app/controllers/questions_controller.rb
  app/javascript/utils/QuestionsUtils.ts
Labels: Team S⊙w⊙T

#227 Feature/#175 calendar feed 3
  Gemfile
  Gemfile.lock
  app/controllers/ical_controller.rb
  app/models/user.rb
  app/views/users/registrations/show.html.erb
  config/routes.rb
  db/migrate/20200120184223_add_hash_id_to_users.rb
  db/schema.rb
  spec/factories/users.rb
  spec/models/user_spec.rb
  spec/views/home/index.html.erb_spec.rb
  spec/views/users/registrations_show.html.erb_spec.rb
Labels: Team Überlapsch

#264 Feature/#238 semantic headlines
  app/javascript/components/AnswerOption.tsx
  app/views/courses/_form.html.erb
  app/views/courses/show.html.erb
  app/views/lectures/_form.html.erb
  app/views/lectures/show.html.erb
  app/views/polls/_form.html.erb
  app/views/polls/new.html.erb
  app/views/polls/show.html.erb
  app/views/uploaded_files/_form.html.erb
  app/views/users/registrations/show.html.erb
Labels: ready to merge

#263 Feature/#202 feedback setting
  app/controllers/feedbacks_controller.rb
  app/controllers/lectures_controller.rb
  app/views/lectures/_form.html.erb
  app/views/lectures/show.html.erb
  db/migrate/20200124140445_add_feedback_enabled_to_lectures.rb
  db/schema.rb
  spec/controllers/feedbacks_controller_spec.rb
  spec/views/lectures/edit.html.erb_spec.rb
  spec/views/lectures/new.html.erb_spec.rb
  spec/views/lectures/show.html.erb_spec.rb
Labels: Team S⊙w⊙T, ready to merge

#265 Add total numbers on bar chart and fix bug
  app/javascript/components/PollResultBarChart.tsx
  app/javascript/utils/PollOptionUtils.ts
Labels: ready to merge

#269 Feature/#259 remove lecture description
  app/controllers/lectures_controller.rb
  app/models/lecture.rb
  app/views/lectures/_form.html.erb
  db/migrate/20200124151237_remove_description_from_lectures.rb
  db/schema.rb
  spec/controllers/lectures_controller_spec.rb
  spec/factories/lectures.rb
  spec/models/lecture_spec.rb
  spec/views/lectures/edit.html.erb_spec.rb
  spec/views/lectures/new.html.erb_spec.rb
  spec/views/lectures/show.html.erb_spec.rb
Labels: Team S⊙w⊙T

#272 Feature/#196 automatic lecture (de) activation
  app/controllers/lectures_controller.rb
  app/controllers/questions_controller.rb
  app/models/lecture.rb
  app/views/courses/_table.html.erb
  app/views/courses/_table_not_running.html.erb
  app/views/courses/_table_only_running.erb
  app/views/home/index.html.erb
  app/views/lectures/_form.html.erb
  app/views/lectures/_tabbar.html.erb
  app/views/lectures/current.html.erb
  app/views/lectures/index.html.erb
  app/views/lectures/show.html.erb
  config/application.rb
  config/routes.rb
  db/schema.rb
  db/seeds.rb
  spec/controllers/lectures_controller_spec.rb
  spec/controllers/questions_controller_spec.rb
  spec/features/courses/show_course_spec.rb
  spec/features/lectures/current_lecture_spec.rb
  spec/features/lectures/show_lecture_spec.rb
  spec/models/lecture_spec.rb
  spec/views/courses/show.html.erb_spec.rb
  spec/views/home/index.html.erb_spec.rb
  spec/views/lectures/current.html.erb_spec.rb
  spec/views/lectures/edit.html.erb_spec.rb
  spec/views/lectures/show.html.erb_spec.rb
Labels: Team PB

#273 Show edit/review buttons for active lectures too
  app/views/courses/_table_only_running.erb
Labels: Team PB

#261 Feature/#230 student dashboard upvote update feed
  app/assets/stylesheets/lecture_updates.scss
  app/controllers/questions_controller.rb
  app/javascript/components/Question.tsx
  app/javascript/components/Update.tsx
  app/javascript/stores/Question.ts
  app/javascript/stores/UpdateItem.ts
  app/models/question.rb
  app/serializers/question_serializer.rb
  spec/controllers/questions_controller_spec.rb
  spec/models/question_spec.rb
Labels: Team PB

#266 Feature/#234 review archived lecture
  .travis.yml
  app/models/lecture.rb
  app/views/courses/_table_not_running.html.erb
  app/views/lectures/show.html.erb
  db/schema.rb
  spec/features/courses/show_course_spec.rb
Labels: ready to merge

#274 Fix seed data by unique ids + fix until loop
  app/models/user.rb
  db/seeds.rb
  spec/models/user_spec.rb
Labels: ready to merge

#276 Feature/#241 rename leave course button
  app/views/courses/show.html.erb
  app/views/home/index.html.erb
  spec/views/courses/show.html.erb_spec.rb
  spec/views/home/index.html.erb_spec.rb
Labels: Team RESTless

#267 unify back button design & position
  app/views/courses/_form.html.erb
  app/views/courses/_table.html.erb
  app/views/courses/_table_not_running.html.erb
  app/views/courses/_table_only_running.erb
  app/views/courses/edit.html.erb
  app/views/courses/index.html.erb
  app/views/courses/new.html.erb
  app/views/courses/show.html.erb
  app/views/home/index.html.erb
  app/views/lectures/_tabbar.html.erb
  app/views/lectures/current.html.erb
  app/views/lectures/edit.html.erb
  app/views/lectures/new.html.erb
  app/views/lectures/show.html.erb
  app/views/polls/_lecturer_table.html.erb
  app/views/polls/_student_table.html.erb
  app/views/polls/answer.html.erb
  app/views/polls/edit.html.erb
  app/views/polls/index.html.erb
  app/views/polls/new.html.erb
  app/views/polls/show.html.erb
  app/views/uploaded_files/new.html.erb
  app/views/users/registrations/show.html.erb
  db/schema.rb
Labels: Team RESTless, ready to merge

#277 Fix not working lecture status scheduler
  app/models/lecture.rb
  config/application.rb
  spec/controllers/lectures_controller_spec.rb
  spec/controllers/questions_controller_spec.rb
Labels: Team PB

#290 Feature/#278 lecture title to 142 chars
  app/models/lecture.rb
Labels: Team Überlapsch

#289 Feature/#280 remove sign up when logged in
  app/views/home/index.html.erb
Labels: Team Überlapsch

#291 Feature/#279 forbid access to course index
  app/controllers/courses_controller.rb
  spec/controllers/courses_controller_spec.rb
Labels: Team Überlapsch

#297 Improvement/#296 restyle student poll views
  app/views/polls/_student_table.html.erb
  app/views/polls/show.html.erb
Labels: Team S⊙w⊙T, ready to merge

#310 Add check whether database exists
  config/application.rb
Labels: Team PB, bug

#271 Implement core and optional feature and tests
  app/controllers/uploaded_files_controller.rb
  app/models/uploaded_file.rb
  app/views/components/_show_uploaded_files_or_links.erb
  app/views/uploaded_files/_form.html.erb
  spec/features/uploadedFiles/upload_new_file_spec.rb
  spec/features/uploadedFiles/uploaded_files_View_in_dashboard_spec.rb
  spec/features/uploadedFiles/uploaded_links_spec.rb
Labels: Team RESTless

#275 Use time_select and date_select to get 24 hour format.
  app/assets/stylesheets/lectures.scss
  app/views/lectures/_form.html.erb
  package-lock.json
  spec/views/lectures/edit.html.erb_spec.rb
  spec/views/lectures/new.html.erb_spec.rb
Labels: Team RESTless, ready to merge

#320 change download targets to _self
  app/views/components/_show_uploaded_files_or_links.erb
Labels: Team RESTless, ready to merge

#323 Remove unused functions
  app/models/lecture.rb
Labels: Team RESTless, ready to merge

#324 save file extensions and append it on download
  app/controllers/uploaded_files_controller.rb
  db/migrate/20200130131908_save_file_extension_for_uploads.rb
  db/schema.rb
  spec/controllers/uploaded_files_controller_spec.rb
  spec/features/uploadedFiles/all_uploaded_files_spec.rb
  spec/features/uploadedFiles/upload_new_file_spec.rb
  spec/features/uploadedFiles/uploaded_file_association_spec.rb
  spec/features/uploadedFiles/uploaded_files_View_in_dashboard_spec.rb
  spec/fixtures/files/LICENSE.md
Labels: Team RESTless

#313 Enhancement/#283 form styling
  app/javascript/components/PollOption.tsx
  app/views/courses/_form.html.erb
  app/views/courses/edit.html.erb
  app/views/courses/new.html.erb
  app/views/lectures/edit.html.erb
  app/views/lectures/new.html.erb
  app/views/polls/_form.html.erb
  app/views/polls/edit.html.erb
  app/views/polls/new.html.erb
  app/views/users/passwords/edit.html.erb
  app/views/users/passwords/new.html.erb
  app/views/users/registrations/edit.html.erb
  app/views/users/registrations/new.html.erb
  app/views/users/sessions/new.html.erb
  app/views/users/shared/_links.html.erb
  db/schema.rb
Labels: Team Überlapsch

#195 Improve lecturer feedback design
  .rubocop.yml
  app/assets/stylesheets/courses.scss
  app/views/lectures/show.html.erb
Labels: Team Überlapsch

#327 Feature/#196 lecturer status updating tests
  spec/factories/lectures.rb
  spec/models/lecture_spec.rb
  spec/rails_helper.rb
Labels: Team PB

#301 Feature/#258 as a lecturer, when i'm in a course and click edit on a lecture, then back i'm not taken to the detail view of the lecture
  spec/views/courses/new.html.erb_spec.rb
Labels: Team S⊙w⊙T, ready to merge

#293 Feature/#260 display course description
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/home.scss
  app/views/home/index.html.erb
  spec/views/home/index.html.erb_spec.rb
Labels: Team S⊙w⊙T, ready to merge

#309 Bugfix/#298 polls orders on deployment
  app/controllers/polls_controller.rb
  app/models/poll.rb
  app/views/polls/_form.html.erb
  app/views/polls/_lecturer_table.html.erb
  app/views/polls/_student_table.html.erb
  db/migrate/20200129225856_add_index_to_poll_options.rb
  db/schema.rb
Labels: Team S⊙w⊙T, ready to merge

#312 Feature/#281 add defaults for lecture time
  app/views/lectures/_form.html.erb
Labels: Team Überlapsch

#288 Feature/#254 add qr code
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/lectures.scss
  app/controllers/lectures_controller.rb
  app/views/lectures/show.html.erb
  config/routes.rb
  spec/controllers/lectures_controller_spec.rb
  spec/features/lectures/current_lecture_spec.rb
  spec/features/lectures/show_lecture_spec.rb
  spec/features/uploadedFiles/upload_new_file_spec.rb
  spec/routing/lectures_routing_spec.rb
  spec/views/lectures/show.html.erb_spec.rb
Labels: Team S⊙w⊙T, ready to merge

#314 Enable polls, feedback according to current lecture status
  app/controllers/feedbacks_controller.rb
  app/controllers/lectures_controller.rb
  app/controllers/polls_controller.rb
  app/views/courses/_table_not_running.html.erb
  app/views/courses/_table_only_running.erb
  app/views/lectures/show.html.erb
  app/views/polls/_lecturer_table.html.erb
  app/views/polls/_student_table.html.erb
  app/views/polls/index.html.erb
  app/views/polls/show.html.erb
  spec/controllers/polls_controller_spec.rb
  spec/features/courses/show_course_spec.rb
  spec/views/lectures/show.html.erb_spec.rb
Labels: Team PB

#341 Fix bug of dejoining students after status change
  app/controllers/lectures_controller.rb
Labels: Team PB

#340 Feature/#326 lecturer code
  README.md
  app/controllers/users/registrations_controller.rb
  app/models/user.rb
  app/views/users/registrations/edit.html.erb
  app/views/users/registrations/new.html.erb
  spec/features/users/user_create_spec.rb
  spec/features/users/user_edit_spec.rb
  spec/views/users/registrastions_edit.html.erb_spec.rb
  spec/views/users/registrations_new.html.erb_spec.rb
Labels: Team RESTless, ready to merge

#344 Bugfix/#328 remove resend password
  app/controllers/users/passwords_controller.rb
  app/views/users/passwords/new.html.erb
  app/views/users/shared/_links.html.erb
  spec/views/users/sessions_new.html.erb_spec.rb
Labels: ready to merge

#347 Restyle start and stop button in polls for the lecture view
  app/assets/stylesheets/courses.scss
  app/assets/stylesheets/lecture_comprehension.scss
  app/assets/stylesheets/lecture_statistics.scss
  app/assets/stylesheets/lecture_updates.scss
  app/assets/stylesheets/polls.scss
  app/assets/stylesheets/questions.scss
  app/assets/stylesheets/scaffolds.scss
  app/javascript/components/ComprehensionLecturer.tsx
  app/javascript/components/ComprehensionStudent.tsx
  app/javascript/components/ParticipantsCount.tsx
  app/javascript/components/QuestionsForm.tsx
  app/javascript/components/QuestionsList.tsx
  app/javascript/components/StatisticsView.tsx
  app/javascript/components/UpdatesList.tsx
  app/views/courses/_form.html.erb
  app/views/courses/show.html.erb
  app/views/lectures/_form.html.erb
  app/views/polls/_form.html.erb
  app/views/polls/edit.html.erb
  app/views/polls/show.html.erb
  app/views/uploaded_files/_form.html.erb
Labels: Team S⊙w⊙T, Visual Enhancement

#352 Open polls close on lecture being archived and cannot be opened afterwards anymore
  app/controllers/polls_controller.rb
  app/models/lecture.rb
  app/models/poll.rb
  spec/controllers/polls_controller_spec.rb
  spec/models/lecture_spec.rb
Labels: Team S⊙w⊙T

#355 fix removing of students when key is added
  app/controllers/lectures_controller.rb
  spec/controllers/lectures_controller_spec.rb
Labels: ready to merge

#348 Feature/#331 restyle delete unenroll
  app/views/courses/_form.html.erb
  app/views/courses/show.html.erb
  app/views/home/index.html.erb
  app/views/lectures/_tabbar.html.erb
  app/views/lectures/edit.html.erb
  app/views/polls/edit.html.erb
  spec/views/lectures/edit.html.erb_spec.rb
Labels: Team RESTless, ready to merge

#358 Feature/#197 updating lecture status in soft realtime
  app/assets/javascripts/lectures.js
  app/channels/lecture_status_channel.rb
  app/models/lecture.rb
  app/views/courses/show.html.erb
  app/views/home/index.html.erb
  app/views/lectures/current.html.erb
  app/views/lectures/index.html.erb
  app/views/lectures/show.html.erb
  spec/controllers/polls_controller_spec.rb
  spec/features/courses/show_course_spec.rb
  spec/models/lecture_spec.rb
  spec/views/lectures/edit.html.erb_spec.rb
Labels: Team PB

#356 Feature/#345 differentiate created and stopped polls
  app/controllers/polls_controller.rb
  app/models/lecture.rb
  app/models/poll.rb
  app/views/polls/_form.html.erb
  app/views/polls/_lecturer_table.html.erb
  app/views/polls/_student_table.html.erb
  app/views/polls/show.html.erb
  db/migrate/20200131150605_remove_is_active_from_polls.rb
  db/migrate/20200131150617_add_status_to_polls.rb
  db/schema.rb
  spec/controllers/polls_controller_spec.rb
  spec/factories/polls.rb
  spec/models/lecture_spec.rb
  spec/views/polls/index.html.erb_spec.rb
Labels: Team S⊙w⊙T, ready to merge

#362 Feature/#342 multiple polls at a time
  app/models/poll.rb
  spec/controllers/polls_controller_spec.rb
Labels: Team S⊙w⊙T

#365 Set line back to where it belonged
  app/models/lecture.rb
Labels: Team S⊙w⊙T, ready to merge

#373 Update lecture.rb
  app/models/lecture.rb
Labels: Team S⊙w⊙T, ready to merge

#372 Feature/#361 auto update poll list
  app/views/polls/_student_table.html.erb
  app/views/polls/index_students.html.erb
Labels: Team S⊙w⊙T

#375 Restore participants icon
  app/javascript/components/ParticipantsCount.tsx
Labels: Team S⊙w⊙T, bug
