Repository hpi-swt2/lecture-portal, pull requests merged in 2020-02, with the labels that each got.

#376 Delete double view button
  app/views/polls/_lecturer_table.html.erb
Labels: Team S⊙w⊙T, bug

#377 Delete unnecessary table rows
  app/views/polls/_lecturer_table.html.erb
  app/views/polls/_student_table.html.erb
Labels: Team S⊙w⊙T, Visual Enhancement, ready to merge

#380 Fix travis build problems
  Dockerfile
  config/database_travis_build.yml
  db/migrate/20200129225856_add_index_to_poll_options.rb
  spec/controllers/lectures_controller_spec.rb
  spec/models/lecture_spec.rb
  spec/views/lectures/edit.html.erb_spec.rb
Labels: Team RESTless, bug, ready to merge

#381 fix ordering of options in your vote view
  app/views/polls/show.html.erb
Labels: Team S⊙w⊙T, bug

#359 Restyle the poll list (Student + lecturer)
  app/assets/stylesheets/polls.scss
  app/views/polls/_lecturer_table.html.erb
  app/views/polls/_student_table.html.erb
  spec/views/polls/index.html.erb_spec.rb
Labels: Team S⊙w⊙T, Visual Enhancement

#364 Feature/#360 create polls in lecture created status
  app/assets/javascripts/lectures.js
  app/controllers/polls_controller.rb
  app/views/courses/_table_not_running.html.erb
  app/views/polls/_lecturer_table.html.erb
  app/views/polls/index.html.erb
  spec/features/courses/show_course_spec.rb
Labels: Team PB

#382 Feature/#379 seperate page to diplay joined students
  app/controllers/lectures_controller.rb
  app/views/lectures/_tabbar.html.erb
  app/views/lectures/show.html.erb
  app/views/lectures/studentList.html.erb
  config/routes.rb
  spec/views/lectures/show.html.erb_spec.rb
  spec/views/lectures/studentList.html.erb_spec.rb
Labels: Team S⊙w⊙T, ready to merge

#338 Feature/284 nothing here yet labels
  app/assets/stylesheets/lectures.scss
  app/assets/stylesheets/polls.scss
  app/javascript/components/UpdatesList.tsx
  app/views/components/_show_uploaded_files_or_links.erb
  spec/factories/uploaded_files.rb
  spec/views/courses/show.html.erb_spec.rb
  spec/views/lectures/show.html.erb_spec.rb
Labels: Team Überlapsch

#371 Make courses deletable again.
  app/models/course.rb
  spec/models/course_spec.rb
Labels: Team RESTless

#369 Default for secret key.
  README.md
  app/models/user.rb
  spec/features/users/user_create_spec.rb
Labels: Team RESTless, ready to merge

#366 Feature/#234 review archived lecture
  db/migrate/20200131143506_migrate_remaining_ended_lectures.rb
Labels: Team RESTless, ready to merge

#384 manually delete answers and/or options in polls controller
  app/controllers/polls_controller.rb
Labels: Team S⊙w⊙T

#383 remove course unenroll button in home
  app/views/home/index.html.erb
  spec/views/home/index.html.erb_spec.rb
Labels: Team RESTless, ready to merge

#389 fix path of qr code to be absolute path
  app/controllers/lectures_controller.rb
Labels: Team S⊙w⊙T

#367 Feature/#331 restyle delete unenroll
  app/views/home/index.html.erb
Labels: Team RESTless, ready to merge

#354 Enhancement/#308 refine button placements
  app/controllers/lectures_controller.rb
  app/views/courses/show.html.erb
  app/views/lectures/_tabbar.html.erb
  app/views/lectures/edit.html.erb
  app/views/lectures/show.html.erb
  db/schema.rb
  spec/controllers/lectures_controller_spec.rb
  spec/views/lectures/edit.html.erb_spec.rb
  spec/views/lectures/show.html.erb_spec.rb
Labels: Team Überlapsch

#387 Bugfix/#385 redirect lecturer to course overview after lecture creation
  app/controllers/lectures_controller.rb
  spec/controllers/lectures_controller_spec.rb
Labels: Team RESTless, ready to merge

#343 Beautify running lectures on home view
  app/views/home/index.html.erb
Labels: Team Überlapsch

#395 Enhancement/#287 mark course description as optional
  app/views/courses/_form.html.erb
  app/views/users/registrations/edit.html.erb
  db/schema.rb
Labels: Team Überlapsch

#353 Enhancement/#311 available courses overview
  app/controllers/courses_controller.rb
  app/controllers/home_controller.rb
  app/views/courses/available.html.erb
  app/views/home/index.html.erb
  config/routes.rb
  spec/views/courses/available.html.erb_spec.rb
  spec/views/home/index.html.erb_spec.rb
Labels: Team Überlapsch

#399 rephrase "feedback submitted" to "feedback saved"
  app/views/lectures/show.html.erb
Labels: Team Überlapsch

#401 Enhancement/#378 running lectures for lecturer
  app/views/home/index.html.erb
Labels: Team Überlapsch

#351 Feature/#332 yes no instead of boolean
  app/views/polls/_lecturer_table.html.erb
  app/views/polls/_student_table.html.erb
  spec/views/polls/index.html.erb_spec.rb
Labels: Team RESTless, ready to merge

#390 Fix/#386 multiple small changes
  app/controllers/polls_controller.rb
  app/views/lectures/studentList.html.erb
  app/views/polls/_lecturer_table.html.erb
  app/views/polls/_student_table.html.erb
  app/views/polls/index_students.html.erb
  app/views/polls/show.html.erb
Labels: Team S⊙w⊙T

#392 bugfix #391 - disable all inputs on settings page
  app/views/lectures/_form.html.erb
  spec/views/lectures/edit.html.erb_spec.rb
Labels: Team RESTless

#403 Enhancement/#285 home view style
  app/assets/stylesheets/home.scss
  app/views/courses/_table.html.erb
  app/views/courses/index.html.erb
  app/views/courses/show.html.erb
  app/views/home/index.html.erb
  app/views/lectures/_table_not_running.html.erb
  app/views/lectures/_table_running.html.erb
  app/views/lectures/index.html.erb
  spec/views/courses/index.html.erb_spec.rb
Labels: Team Überlapsch

#408 Change title of running lecture tables
  app/views/courses/show.html.erb
  app/views/home/index.html.erb
Labels: Team Überlapsch

#396 #234 - make archived lectures viewable to course students
  app/controllers/lectures_controller.rb
  app/views/lectures/show.html.erb
  spec/controllers/lectures_controller_spec.rb
Labels: Team RESTless, ready to merge

#349 Bug/#335 error when deleting account
  app/models/user.rb
  db/migrate/20200131101229_remove_lecture_id_from_courses.rb
  db/schema.rb
  spec/models/user_spec.rb
Labels: Team RESTless, ready to merge

#400 Hide deactivated features entirely
  app/views/lectures/_tabbar.html.erb
  app/views/lectures/show.html.erb
  spec/views/lectures/show.html.erb_spec.rb
Labels: Team RESTless, design leads

#409 Bug/question update ui
  app/javascript/components/UpdatesList.tsx
  app/javascript/stores/QuestionsList.ts
  app/javascript/utils/UpdatesUtils.ts
  db/schema.rb
Labels: Team PB, bug

#405 throw error if wrong secret key is provided
  app/controllers/users/registrations_controller.rb
  app/models/lecture.rb
  app/models/user.rb
  spec/features/users/user_create_spec.rb
Labels: Team RESTless, WIP, question, ready to merge
